Lavacar.UI/Controllers/HomeController.cs
using Lavacar.Presentacion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lavacar.Presentacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lavacar.UI/Controllers/ServiciosController.cs
using Lavacar.Entidades;
using Lavacar.Entidades.Enum;
using Lavacar.Entidades.Helpers;
using Lavacar.LogicaNegocio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lavacar.Presentacion.Controllers
{
    public class ServiciosController : Controller
    {
        private readonly LogicaServicio _logicaServicio;
        private readonly LogicaVehiculo _logicaVehiculo;

        public ServiciosController(LogicaServicio logicaServicio, LogicaVehiculo logicaVehiculo)
        {
            _logicaServicio = logicaServicio;
            _logicaVehiculo = logicaVehiculo;
        }

        public async Task<IActionResult> ListaDeServicios(string id)
        {
            var listaDeServicios = await _logicaServicio.ListarTodosLosServicios();

            ViewBag.Mensaje = id;

            return View(listaDeServicios);         
        }

        public async Task<JsonResult> ListarServicios()
        {
            var listaDeServicios = await _logicaServicio.ListarTodosLosServicios();

            return Json(listaDeServicios);
        }

        public IActionResult AgregarServicio()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarServicio(Servicio servicio)
        {
            Respuesta respuesta;

            try
            {
                if (ModelState.IsValid)
                {
                    respuesta = await _logicaServicio.AgregarServicio(servicio);

                    return Json(respuesta);
                }
                else
                {
                    respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.Incorrecto, "") };

                    return Json(respuesta);
                }

            }
            catch
            {
                respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.ErrorSolicitud, "") };

                return Json(respuesta);
            }
        }

        public async Task<IActionResult> EditarServicio(int id)
        {
            var servicio = await _logicaServicio.ObtenerServicioPorId(id);

            return View(servicio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> EditarServicio(Servicio servicio)
        {
            Respuesta respuesta;

            try
            {
                if (ModelState.IsValid)
                {
                    respuesta = await _logicaServicio.EditarServicio(servicio);

                    return Json(respuesta);

                }
                else
                {

                    respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.Incorrecto, "") };

                    return Json(respuesta);
                }

            }
            catch (Exception e)
            {
                respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.ErrorSolicitud, e.Message) };

                return Json(respuesta);
            }

        }

        [HttpPost]
        public async Task<JsonResult> EliminarServicio(int id)
        {
            Respuesta respuesta;

            try
            {
                respuesta = await _logicaServicio.EliminarServicio(id);

                return Json(respuesta);

            }
            catch
            {

                respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.ErrorSolicitud, "") };

                return Json(respuesta);
            }

        }

        public async Task<IActionResult> VehiculosPorServicio(int id, string descripcion)
        {
            var listaDeServicios = await _logicaVehiculo.ListarVehiculosPorServicio(id);

            ViewBag.Servicio = descripcion;

            return View(listaDeServicios);
        }

       
    }

}

Lavacar.UI/Controllers/VehiculosController.cs
using Lavacar.Entidades;
using Lavacar.Entidades.Enum;
using Lavacar.Entidades.Helpers;
using Lavacar.LogicaNegocio;
using Lavacar.Presentacion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lavacar.Presentacion.Controllers
{
    public class VehiculosController : Controller
    {
        private readonly LogicaVehiculo _logicaVehiculo;

        public VehiculosController(LogicaVehiculo logicaVehiculo)
        {
            _logicaVehiculo = logicaVehiculo;
        }
        public async Task<IActionResult> ListaDeVehiculos(string id)
        {
            var listaDeVehiculos = await _logicaVehiculo.ListarTodosLosVehiculos();

            ViewBag.Mensaje = id;

            return View(listaDeVehiculos);
        }

        public IActionResult AgregarVehiculo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarVehiculo(VehiculoVM vehiculo)
        {
            Respuesta respuesta;

            try
            {
                if (ModelState.IsValid)
                {

                    var nuevoVehiculo = new Vehiculo
                    {
                        IdVehiculo = 0,
                        Dueno = vehiculo.Dueno,
                        Marca = vehiculo.Marca,
                        Placa = vehiculo.Placa,
                        ListaServicios = vehiculo.ListaServicios
                    };

                    respuesta = await _logicaVehiculo.AgregarVehiculo(nuevoVehiculo);

                    return Json(respuesta);
                }
                else
                {
                    respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.Incorrecto, "") };

                    return Json(respuesta);
                }

            }
            catch
            {
                respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.ErrorSolicitud, "") };

                return Json(respuesta);
            }
        }

        public async Task<IActionResult> EditarVehiculo(int id)
        {
            var vehiculo = await _logicaVehiculo.ObtenerVehiculoPorId(id);

            var vehiculoVM = new VehiculoVM
            {
                IdVehiculo = vehiculo.IdVehiculo,
                Dueno = vehiculo.Dueno,
                Placa = vehiculo.Placa,
                Marca = vehiculo.Marca
            };

            return View(vehiculoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> EditarVehiculo(VehiculoVM vehiculo)
        {
            Respuesta respuesta;

            try
            {
                if (ModelState.IsValid)
                {
                    var vehiculoEditado = new Vehiculo
                    {
                        IdVehiculo = vehiculo.IdVehiculo,
                        Dueno = vehiculo.Dueno,
                        Marca = vehiculo.Marca,
                        Placa = vehiculo.Placa,
                        ListaServicios = vehiculo.ListaServicios
                    };

                    respuesta = await _logicaVehiculo.EditarVehiculo(vehiculoEditado);

                    return Json(respuesta);

                }
                else
                {

                    respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.Incorrecto, "") };

                    return Json(respuesta);
                }

            }
            catch (Exception e)
            {
                respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.ErrorSolicitud, e.Message) };

                return Json(respuesta);
            }

        }

        [HttpPost]
        public async Task<JsonResult> EliminarVehiculo(int id)
        {
            Respuesta respuesta;

            try
            {
                respuesta = await _logicaVehiculo.EliminarVehiculo(id);

                return Json(respuesta);

            }
            catch
            {

                respuesta = new Respuesta { Ok = false, Mensaje = HelperMensaje.GenerarMensaje(TipoMensaje.ErrorSolicitud, "") };

                return Json(respuesta);
            }

        }

        public async Task<JsonResult> ObtenerIdServiciosDeVehiculo(int id)
        {
            var ListaIdServicios = await _logicaVehiculo.ObtenerIdServiciosDeVehiculo(id);

            return Json(ListaIdServicios);
        }


    }
}

Lavacar.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div style="background-color:#96E6DA" class="card shadow mb-2">
    <div class="card-header py-lg-3 text-center">
        <h2 class="m-0 font-weight-light text-secondary"><samp>Lavacar Katse - ¡Gracias por preferirnos!</samp></h2>
    </div>

</div>



<div style="background-color:#96E6DA" class="card-body col-md-auto" >

    <div class="row w-100 justify-content-center" >
        <img src="/img/carwash1.png" alt="" height="300" width="400">

        


    </div>

    <div class="row w-100 justify-content-center d-inline-flex">


        <div class="col-xl-5 col-md-11 mb-4 mx-md-n5 mx-xl-0">
            <div class="card border-bottom-left-cnp shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="h3 font-weight-light text-uppercase mb-1 text-center">
                                <div class="mb-3 mx-1">
                                    <a asp-area="" asp-controller="Servicios" asp-action="ListaDeServicios">
                                        <span class="fas fa-list-ol"></span>
                                        Servicios
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-xl-5 col-md-11 mb-4 mx-md-n5 mx-xl-0">
            <div class="card border-bottom-left-cnp shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="h3 font-weight-light text-center text-uppercase mb-1">
                                <div class="h3 font-weight-light text-uppercase mb-1 text-center">
                                    <div class="mb-3 mx-1">
                                        <a asp-area="" asp-controller="Vehiculos" asp-action="ListaDeVehiculos">
                                            <span class="fas fa-car-side"></span>
                                            Vehículos
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>